spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/mini-oauth
spring.datasource.username=dbuser
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=none
#spring.sql.init.separator=^^
spring.sql.init.mode=always

minioauth.auth_secret=super-secret-2026
minioauth.accessttl=900
minioauth.refreshttl=5
minioauth.skew=super-secret-2026
minioauth.issuer=mini-auth
